### ISSUE TITLE
Data source does not exist

### ISSUE THREAD

**Issue by xingyuz233** [SoftWiser-group/iTag#1]
Hello, i think i met some problems when running your sample code. 
File "itag.py",  line 124
No such file '../askubuntu/au_259740.npz'
Would you please tell how to get this file or where to find it?
Thanks a lot.

**Comment by ZzYuanYaozZ** [comment]
Hi, 

Sorry for the inconvenience. 
The file is the input data stored in numpy format.
You may adjust the code to read in your own data files.
