### ISSUE TITLE
请教问一下npz文件中的tag数据的构成

### ISSUE THREAD

**Issue by shuiqukeyou** [SoftWiser-group/iTag#6]
我看到源码中的参数设置部分中有这么两句：
`LABEL_VOCAB = 2500`
`DE_TOKENS = LABEL_VOCAB - 2  # remove pad and start tokens from file_vocab`

loaddata 函数是根据 LABEL_VOCAB 的值剔除超过其大小的tag的，我猜测 LABEL_VOCAB 是全tag的数量。

但在主文件里面，y_train的one-hot编码使用了 DE_TOKENS 长度的向量进行编码。比全tag数量少了2，而在注释里写着 DE_TOKENS 是 LABEL_VOCAB 删除掉填充符和起始符号后的值

请问数据中tag的构成是有起始符号和填充符号吗？如果有的话是怎样构成的

例如设定每篇文章tag数为5，然后假设一篇具体的文章tag数为3（假设为[124，6，33]）
最终在npz文件中这篇tag的构成是这样吗：[start，124，6，33，pad，pad]

**Comment by Tangworld** [comment]
你好，你可以尝试如下例子，从而理解dataset的构成：
数据为：
brs =[[3, 1, 2, 4],[3,2,1,6],[6,7,1,5]]
sfs =[[1,2],[1,2],[1]]
ms = [[0,1,0,1],[0,1,1,1],[1,1,0,0]]
shared.txt : {3:1,1:2}

示例代码为：
```
import numpy as np
import shared_dataset as sh


def create_data():
	brs = np.array([[3, 1, 2, 4],[3,2,1,6],[6,7,1,5]])
	ms = np.array([[0,1,0,1],[0,1,1,1],[1,1,0,0]])
	sfs = np.array([[1,2],[1,2],[1]])
	np.savez('test.npz', brs=brs, ms=ms, sfs=sfs)

def main():
	(en_train, ms_train, de_train, y_train), (en_test, ms_test, de_test, y_test) = sh.load_data(path='test.npz', num_words=10000, num_sfs=1003)
	print(en_train)
	print(ms_train)
	print(de_train)
	print(y_train)
	print('--------------------------------')
	print(en_test)
	print(ms_test)
	print(de_test)
	print(y_test)



if __name__ == '__main__':
	create_data()
	main()
```

**Comment by shuiqukeyou** [comment]
好的， 十分感谢
